### ISSUE TITLE
Error when I ''cabal install'' in language

### ISSUE THREAD

**Issue by Alvinsjq** [hbasold/LAMA#2]
shijiandeMacBook-Pro:language alvin$ cabal install
Warning: --root-cmd is no longer supported, see
https://github.com/haskell/cabal/issues/3353 (if you didn't type --root-cmd,
comment out root-cmd in your ~/.cabal/config file)
Resolving dependencies...
Configuring language-lama-0.1...
Building language-lama-0.1...
Failed to install language-lama-0.1
Build log ( /Users/alvin/.cabal/logs/ghc-8.2.2/language-lama-0.1-KMwpHKY3lZSB1jgmMQSKz3.log ):
cabal: Entering directory '.'
Configuring language-lama-0.1...
Preprocessing library for language-lama-0.1..
Building library for language-lama-0.1..
[ 2 of 27] Compiling Data.Graph.Inductive.GenShow ( lib/Data/Graph/Inductive/GenShow.hs, dist/build/Data/Graph/Inductive/GenShow.o )

lib/Data/Graph/Inductive/GenShow.hs:9:10: error:
    **Duplicate instance declarations:**
      instance (Show a, Show b) => Show (Gr a b)
        -- Defined at lib/Data/Graph/Inductive/GenShow.hs:9:10
      instance (Show a, Show b) => Show (Gr a b)
        -- Defined in ‘Data.Graph.Inductive.PatriciaTree’
  |
9 | instance forall a b. (Show a, Show b) => Show (Gr a b) where
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
language-lama-0.1-KMwpHKY3lZSB1jgmMQSKz3 failed during the building phase. The
exception was:
ExitFailure 1

-------------------------
I have a question that 
why did I catch the error "Duplicate instance declarations:" ?

Thank you!

**Comment by hbasold** [comment]
Thank you for the report!

This was caused by a newer version of fgl, in which Show is already implemented for Patricia trees. I fixed this now.
